name = "PapersRegistry"
uuid = "a2bf4cdf-b68e-408d-aa7b-1a4eaf512f7d"
repo = "git@github.com:milonemario/PapersRegistry.git"
description = "Papers Registry"

[packages]
66ca4ba2-e783-4bf3-9259-cde0bbbce19d = { name = "ResidualIncome", path = "R/ResidualIncome" }
